largest number section
SofiaPutlyuk/Games-Project pull request #5
Opened 2024-07-18 15:57 UTC by melk1ns

2024-08-06 10:46 UTC, marianaD4 requested changes

2024-08-06 10:46 UTC, marianaD4 commented on index.html
> +            type="number"
уважно із розділенням блоків та елементів

2024-08-06 10:46 UTC, marianaD4 commented on scss/components/_largest-number.scss
> +      height: 15px;
для тексту не задаємо зазвичай фіксовану висоту. Краще min/max

2024-08-06 10:46 UTC, marianaD4 commented on scss/components/_largest-number.scss
> +      @extend %main-font;
переміщаємо на початок, а потім додаємо додаткові стилі

2024-08-20 12:27 UTC, SofiaPutlyuk commented
Вибачте за те, що зробила merge без затвердження. Будь ласка, залиште коментарі, якщо є помилки, і я їх виправлю. Я створю нову гілку для виправлень.

2024-08-20 12:39 UTC, merged